kumuluzee:
  name: rso-airline-search
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: ${KUMULUZEE_DATASOURCES0_CONNECTIONURL}
    username: ${KUMULUZEE_DATASOURCES0_USERNAME}
    password: ${KUMULUZEE_DATASOURCES0_PASSWORD}
    max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/fri_airline
  config:
    etcd:
      hosts: http://127.0.0.1:2379
  discovery:
    etcd:
      hosts: http://127.0.0.1:2379
    ttl: 30
    ping-interval: 5
  metrics:
    web-instrumentation:
    - name: search-endpoint
      url-pattern: /v1/*