kumuluzee:
  name: rso-airline-search
  version: 1.0.0
  env:
    name: dev

  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: jdbc:postgresql://192.168.99.100:5432/fri_airline
    username: postgres
    password: pass
    max-pool-size: 20