kumuluzee:
  name: rso-airline-search
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: ${KUMULUZEE_DATASOURCES0_CONNECTIONURL}
    username: postgres
    password: pass
    max-pool-size: 20